<?php

/**
 * @file
 * Primary module hooks for Licenses module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function licenses_theme() {
  return [
    'license' => [
      'variables' => [
        'full_name' => NULL,
        'identifier' => NULL,
        'osi_approved' => NULL,
        'deprecated' => NULL,
      ],
    ],
  ];
}
